### ISSUE TITLE
Sync local transcriptions without images

### ISSUE THREAD

**Issue by EvaMLang** [Transkribus/TranskribusSwtGui#102]
leads to the following error:

java.io.IOException: Folder C:\Users\lange\Desktop\GT\GT does not contain any image files!
	at eu.transkribus.core.io.LocalDocReader.findImgFiles(LocalDocReader.java:589)
	at eu.transkribus.core.io.LocalDocReader.load(LocalDocReader.java:178)
	at eu.transkribus.core.io.LocalDocReader.load(LocalDocReader.java:91)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.syncWithLocalDoc(TrpMainWidget.java:3972)
	at eu.transkribus.swt_gui.mainwidget.menubar.TrpMenuBarListener.lambda$addMenuBindings$14(TrpMenuBarListener.java:74)
	at eu.transkribus.swt.util.SWTUtil$8.widgetSelected(SWTUtil.java:1394)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.eclipse.jface.window.Window.runEventLoop(Window.java:825)
	at org.eclipse.jface.window.Window.open(Window.java:801)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.openJobsDialog(TrpMainWidget.java:4280)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidgetViewListener.lambda$addListener$5(TrpMainWidgetViewListener.java:63)
	at eu.transkribus.swt.util.SWTUtil$8.widgetSelected(SWTUtil.java:1394)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$15.run(TrpMainWidget.java:2410)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2370)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2354)
	at eu.transkribus.swt_gui.TrpGui.main(TrpGui.java:98)

My use case would be to duplicate a document given a specific version (any version marked as GT) to another document (currently deep copy of the same TrpDoc). I could either revise any additional tests run on the original TrpDoc or download the respective PAGE XML files in order to upload them again one by one.

Any suggestion?

**Comment by EvaMLang** [comment]
closed by last commit in dev_eva
