### ISSUE TITLE
TipOfTheDay widget not working on Ubuntu 17.04

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#131]
Probably libwebkitgtk-1.0-0 has to be installed?

TODO:
* Confirm error reason
Then
* implement workaround if possible 
OR
* Alter installation instructions on Wiki etc.

Exception is:
```
ERROR [main] eu.transkribus.swt_gui.mainwidget.TrpMainWidget - PROGRAM EXIT WITH FATAL ERROR: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
org.eclipse.swt.SWTError: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
        at org.eclipse.swt.SWT.error(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.eclipse.swt.browser.Mozilla.initMozilla(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.eclipse.swt.browser.Mozilla.create(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.eclipse.swt.browser.Browser.<init>(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.mihalis.opal.tipOfTheDay.TipOfTheDay.buildTip(Unknown Source) ~[opal-1.0.1.jar:na]
        at org.mihalis.opal.tipOfTheDay.TipOfTheDay.open(Unknown Source) ~[opal-1.0.1.jar:na]
        at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.showTipsOfTheDay(TrpMainWidget.java:384) [Transkribus-1.3.2.jar:na]
        at eu.transkribus.swt_gui.mainwidget.menubar.TrpMenuBarListener.lambda$addMenuBindings$20(TrpMenuBarListener.java:86) ~[Transkribus-1.3.2.jar:na]
        at eu.transkribus.swt.util.SWTUtil$8.widgetSelected(SWTUtil.java:1394) ~[Transkribus-1.3.2.jar:na]
        at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source) ~[swt-4.5-linux64.jar:na]
        at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$15.run(TrpMainWidget.java:2420) ~[Transkribus-1.3.2.jar:na]
        at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332) ~[observable-1.4.1.v20120521-2329.jar:na]
        at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2380) [Transkribus-1.3.2.jar:na]
        at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2364) [Transkribus-1.3.2.jar:na]
        at eu.transkribus.swt_gui.TrpGui.main(TrpGui.java:98) [Transkribus-1.3.2.jar:na]
```

**Comment by funkyfuture** [comment]
i can confirm that the installation of `libwebkitgtk-1.0-0` solves the issue.

**Comment by kahlep** [comment]
Thanks for letting us know!

Respective info is added to [Transkribus Wiki](https://transkribus.eu/wiki/index.php/Download_and_Installation#Notes_for_first_launch_on_Linux)

TODO:
* check if the problem is with SWT or [TipOfTheDay](https://github.com/lcaron/opal/wiki/TipOfTheDay) and find workaround if possible

**Comment by jkloe** [comment]
- The problem is the TipOfTheDay widget which uses HTML formatting and thus needs the webkitgtk lib on Ubuntu.
- A workaround might not be feasible as the TipOfTheDay widget was not updated for a long time and is most probably not really needed by most users...

**Comment by EvaMLang** [comment]
Latest dev team decision was to phase out TipsOfTheDay and replace with direct link to https://transkribus.eu/wiki/index.php/How_to_Guides instead
