### ISSUE TITLE
OutOfMemoryError when loading document

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#145]
This message often occurs when loading large image data in Transkribus mostly on Windows systems.
A problematic document is e.g. doc ID = 24838.

```
java.lang.OutOfMemoryError: Java heap space
    at org.eclipse.swt.graphics.Image.getImageData(Unknown Source)
~[swt-4.5-win32.jar:na] 
    at eu.transkribus.swt_gui.canvas.CanvasImage.<init>(CanvasImage.java:41)
~[Transkribus-1.1.2.jar:na]
    at
eu.transkribus.swt_gui.mainwidget.ImageDataDacheFactory.createFromKey(ImageDataDacheFactory.java:55)
...
```

**Comment by jkloe** [comment]
Other example document (reproduced on a Win7 machine with 1 GB of RAM): 25209

**Comment by kahlep** [comment]
In some cases this issue could be sorted out by reinstalling the 64 bit version of Java when the 32 bit version was installed, although the memory allocated to the JVM was even below 1 GiB.
If the OS' architecture can be somehow read from the system properties, a warning message could be displayed to notify the user about an "incorrect" Java version.
