### ISSUE TITLE
CollectionUsersWidget: only show roles that are allowed to be set

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#162]
An editor is not allowed to set someone as owner in a collection but that role is shown to be selected.
When doing so the subsequent error causes an SWTException:
```
org.eclipse.swt.SWTException: Widget is disposed
	at org.eclipse.swt.SWT.error(Unknown Source) ~[org.eclipse.swt.gtk.linux.x86_64-4.7.1.jar:na]
	at org.eclipse.swt.SWT.error(Unknown Source) ~[org.eclipse.swt.gtk.linux.x86_64-4.7.1.jar:na]
	at org.eclipse.swt.SWT.error(Unknown Source) ~[org.eclipse.swt.gtk.linux.x86_64-4.7.1.jar:na]
	at org.eclipse.swt.widgets.Widget.error(Unknown Source) [org.eclipse.swt.gtk.linux.x86_64-4.7.1.jar:na]
	at org.eclipse.swt.widgets.Widget.checkWidget(Unknown Source) [org.eclipse.swt.gtk.linux.x86_64-4.7.1.jar:na]
	at org.eclipse.swt.widgets.Control.setEnabled(Unknown Source) ~[org.eclipse.swt.gtk.linux.x86_64-4.7.1.jar:na]
	at eu.transkribus.swt_gui.collection_manager.CollectionUsersWidget.updateBtnVisibility(CollectionUsersWidget.java:193) ~[classes/:na]
	at eu.transkribus.swt_gui.collection_manager.CollectionUsersWidget.updateUsersForSelectedCollection(CollectionUsersWidget.java:234) ~[classes/:na]
	at eu.transkribus.swt_gui.collection_manager.CollectionUsersWidgetListener.addSelectedUsersToCollection(CollectionUsersWidgetListener.java:261) ~[classes/:na]
	at eu.transkribus.swt_gui.collection_manager.CollectionUsersWidgetListener.widgetSelected(CollectionUsersWidgetListener.java:98) ~[classes/:na]
```

**Comment by hackmanschorsch** [comment]
Fixed. An editor is not allowed to change the role of an user via Rest API - so this is also implemented in the GUI. Editor can add users and remove users with user.role <= his.role. Transcriber and Reader cannot do all of that. Found and fixed 'widget is disposed' bug.
