### ISSUE TITLE
Destination 'config.properties' exists but is read-only

### ISSUE THREAD

**Issue by kimpham54** [Transkribus/TranskribusSwtGui#214]
When I go to Profiles and try to access the Transcription view, I get this error message. config.properties is read only, and I am unable to save my own profile

Destination 'config.properties' exists but is read-only

Exception:
java.io.IOException: Destination 'config.properties' exists but is read-only
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1089)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:1038)
	at eu.transkribus.swt_gui.TrpConfig.loadProfile(TrpConfig.java:357)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.selectProfile(TrpMainWidget.java:4449)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.changeProfileFromUi(TrpMainWidget.java:4729)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidgetViewListener.lambda$addListener$25(TrpMainWidgetViewListener.java:146)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidgetViewListener$$Lambda$102/244185498.accept(Unknown Source)
	at eu.transkribus.swt.util.SWTUtil$8.widgetSelected(SWTUtil.java:1512)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at eu.transkribus.swt.util.DropDownToolItem$DropdownSelectionListener.selectItem(DropDownToolItem.java:253)
	at eu.transkribus.swt.util.DropDownToolItem$DropdownSelectionListener$3.widgetSelected(DropDownToolItem.java:152)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$15.run(TrpMainWidget.java:2594)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2548)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2529)
	at eu.transkribus.swt_gui.TrpGui.main(TrpGui.java:98)

<img width="1375" alt="screen shot 2018-08-15 at 9 40 56 am" src="https://user-images.githubusercontent.com/2915770/44157302-602a5080-a06f-11e8-920f-0c0b0fffb0c5.png">

**Comment by kimpham54** [comment]
I upgraded Transkribus to 1.4.3 and this is no longer an issue.
