### ISSUE TITLE
 Exception when merging cells of a table

### ISSUE THREAD

**Issue by hackmanschorsch** [Transkribus/TranskribusSwtGui#254]
Bug report of user: 
I got this error when I selected all cells in the bottom row of a table and tried to merge them.

OS: Mac OS X
Java version: 1.8.0_45
Java platform architecture: 64
System architecture: 64
File encoding: UTF-8

**Comment by jkloe** [comment]
Two exception occured:

2018-10-30 15:52:44,449 [main] WARN  eu.transkribus.swt_gui.transcription.ATranscriptionWidget - warning: could not compute line bound for line: 58 - returning null!
2018-10-30 15:52:44,685 [main] WARN  eu.transkribus.swt_gui.transcription.ATranscriptionWidget - warning: could not compute line bound for line: 58 - returning null!
2018-10-30 15:52:46,500 [main] ERROR eu.transkribus.swt_gui.mainwidget.TrpMainWidget - Unexpected error occured: Index out of bounds
java.lang.IllegalArgumentException: Index out of bounds
	at org.eclipse.swt.SWT.error(SWT.java:4576)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.custom.StyledText.getLineAtOffset(StyledText.java:3968)
	at eu.transkribus.swt_gui.transcription.ATranscriptionWidget.updateLineStylesForCharacterOffsets(ATranscriptionWidget.java:1424)
	at eu.transkribus.swt_gui.transcription.LineTranscriptionWidget$1.modifyText(LineTranscriptionWidget.java:90)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:37)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7376)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8230)
	at org.eclipse.swt.custom.StyledText.doBackspace(StyledText.java:2306)
	at org.eclipse.swt.custom.StyledText.invokeAction(StyledText.java:7155)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6018)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6045)


2018-10-30 16:22:41,825 [main] INFO  eu.transkribus.swt_gui.mainwidget.TrpMainWidget - selecting profile: Segmentation
2018-10-30 16:23:25,735 [main] ERROR eu.transkribus.swt_gui.mainwidget.TrpMainWidget - Error merging elements - Could not merge elements - null
java.lang.NullPointerException: null
	at eu.transkribus.swt_gui.canvas.listener.CanvasSceneListener.onMerge(CanvasSceneListener.java:771)
	at eu.transkribus.swt_gui.canvas.listener.ICanvasSceneListener.triggerEventMethod(ICanvasSceneListener.java:106)
	at eu.transkribus.swt_gui.canvas.CanvasScene.notifyAllListener(CanvasScene.java:1188)
	at eu.transkribus.swt_gui.canvas.CanvasScene.notifyOnShapesMerged(CanvasScene.java:1108)
	at eu.transkribus.swt_gui.canvas.editing.CanvasShapeEditor.mergeSelectedTableCells(CanvasShapeEditor.java:1787)
	at eu.transkribus.swt_gui.canvas.editing.CanvasShapeEditor.mergeSelected(CanvasShapeEditor.java:342)
	at eu.transkribus.swt_gui.canvas.CanvasToolBarSelectionListener.widgetSelected(CanvasToolBarSelectionListener.java:172)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4292)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4116)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3733)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$15.run(TrpMainWidget.java:2801)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2754)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget.show(TrpMainWidget.java:2735)
	at eu.transkribus.swt_gui.TrpGui.main(TrpGui.java:98)
