### ISSUE TITLE
Transkribus 1.9.1 fails on export

### ISSUE THREAD

**Issue by M3ssman** [Transkribus/TranskribusSwtGui#294]
Hello,

## Actual Behavior

I'm facing a NPE when I try to export Transcriptions from local Files/Images as ALTO + PAGE with Transkribus 1.9.1 Client GUI and there's no data in the chosen export-Destination.

[ulb-sachsen-anhalt-transkribus-1.9.1-01.zip](https://github.com/Transkribus/TranskribusSwtGui/files/3983778/ulb-sachsen-anhalt-transkribus-1.9.1-01.zip)

## Expected Behavior

Export Data in PAGE and ALTO and do not yield Errors.

Please note
_I've attached the root doc.xml as well as the output into the page-Subfolder which gets created in the ZIP-File. The actual TIF-File is not included_

## Plattform
Starting Transkribus - first trying to find java, your OS = linux-gnu
Found java executable in PATH
Java bin = java
Checking java version of: java
Java version = 1.8.0_232 (OpenJDK)

## Reproduce
1. Open Folder with large Tif-Image (7346 x 10791)
2. Include some minimal Transcriptions
3. Click "Export document" => "Export options" [check also "Export ALTO", otherwise defaults] => "OK"

=> Opens Error Dialog Pane

stdout-Log
```
14:17:50.457 WARN  [pool-15-thread-1] eu.transkribus.core.io.LocalDocWriter - Could not update transcript image dimensions - page object is null - should not happen for local docs: file:/home/hartwig/Dokumente/Quarantaene/Transkibus-1.9.1./page/1681877805_J_0006_0004.xml
14:17:58.134 ERROR [main] eu.transkribus.swt_gui.mainwidget.TrpMainWidget - Export error - Error during export of document - null
java.lang.NullPointerException: null
	at eu.transkribus.swt_gui.mainwidget.storage.Storage.exportDocument(Storage.java:2305)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$28.run(TrpMainWidget.java:4070)
	at eu.transkribus.swt.progress.ProgressBarDialog$1.call(ProgressBarDialog.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
14:17:59.653 ERROR [main] eu.transkribus.swt_gui.mainwidget.TrpMainWidget - Export error - null - null
java.lang.NullPointerException: null
	at eu.transkribus.swt_gui.mainwidget.storage.Storage.exportDocument(Storage.java:2305)
	at eu.transkribus.swt_gui.mainwidget.TrpMainWidget$28.run(TrpMainWidget.java:4070)
	at eu.transkribus.swt.progress.ProgressBarDialog$1.call(ProgressBarDialog.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by stweil** [comment]
I get the same error when trying to export PAGE.

Software used: Transkribus-1.9.1 with OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-2, mixed mode, sharing).

**Comment by M3ssman** [comment]
After some experiments we found a working combination with Transkribus 1.5.4 and Oracle Java 1.8.0_131-b11 to export Data as PAGE and ALTO.

On can even import existing ALTO Data and have Transkribus transform this into it's own PAGE Data, when the input ALTO is V2.

BUT

using the same Oracle Java Version as above, an update to Transkribus 1.6.0 results in a similar (silent) export issue. Looks like the client export is already broken since Version 1.6.0 ?

**Comment by M3ssman** [comment]
Actually this has been transferred to https://github.com/ulb-sachsen-anhalt/TranskribusSwtGui/issues/1
