### ISSUE TITLE
Download of update aborts

### ISSUE THREAD

**Issue by kahlep** [Transkribus/TranskribusSwtGui#297]
User reported that the download of updates aborts.

No error in tomcat log, but the content-length in the apache log differs on subsequent tries: 

```
<IP of user> - - [28/Feb/2020:14:21:26 +0100] "POST /TrpServer/rest/downloadClientFileNew?isRelease=false&fileName=Transkribus-1.10.1.1-SNAPSHOT-package.zip HTTP/1.1" 200 8945112
<IP of user> - - [28/Feb/2020:14:24:37 +0100] "GET /TrpServer/rest/availableClientFiles?isRelease=true HTTP/1.1" 200 299
<IP of user> - - [28/Feb/2020:14:24:37 +0100] "GET /TrpServer/rest/availableClientFiles?isRelease=false HTTP/1.1" 200 319
<IP of user> - - [28/Feb/2020:14:24:44 +0100] "POST /TrpServer/rest/downloadClientFileNew?isRelease=false&fileName=Transkribus-1.10.1.1-SNAPSHOT-package.zip HTTP/1.1" 200 9395232
8
```

Error on client: 
```
2020-02-28 14:27:45,983 [main] ERROR eu.transkribus.swt_gui.mainwidget.TrpMainWidget - IO-Error during update - Error during update: 

invalid code lengths set - invalid code lengths set
java.util.zip.ZipException: invalid code lengths set
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:164)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at eu.transkribus.util.SebisZipUtils.unzip(SebisZipUtils.java:87)
	at eu.transkribus.swt_gui.dialogs.ProgramUpdaterDialog$3.run(ProgramUpdaterDialog.java:277)
	at eu.transkribus.swt.progress.ProgressBarDialog$1.call(ProgressBarDialog.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by kahlep** [comment]
Same user reported that the current release could still not be downloaded.

```
2020-03-07 11:10:18,136 [main] ERROR eu.transkribus.swt_gui.mainwidget.TrpMainWidget - IO-Error during update - Error during update: 

Unexpected end of ZLIB input stream - Unexpected end of ZLIB input stream
java.io.EOFException: Unexpected end of ZLIB input stream
	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:194)
	at java.io.FilterInputStream.read(FilterInputStream.java:107)
	at eu.transkribus.util.SebisZipUtils.unzip(SebisZipUtils.java:87)
	at eu.transkribus.swt_gui.dialogs.ProgramUpdaterDialog$3.run(ProgramUpdaterDialog.java:277)
	at eu.transkribus.swt.progress.ProgressBarDialog$1.call(ProgressBarDialog.java:135)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Server log again shows different content-length values transmitted:

```
<IP of user> - - [07/Mar/2020:11:06:50 +0100] "POST /TrpServer/rest/downloadClientFileNew?isRelease=true&fileName=Transkribus-1.10.1-package.zip HTTP/1.1" 200 8830536
<IP of user> - - [07/Mar/2020:11:14:50 +0100] "POST /TrpServer/rest/downloadClientFileNew?isRelease=true&fileName=Transkribus-1.10.1-package.zip HTTP/1.1" 200 8355864
<IP of user> - - [07/Mar/2020:13:33:53 +0100] "POST /TrpServer/rest/downloadClientFileNew?isRelease=true&fileName=Transkribus-1.10.1-package.zip HTTP/1.1" 200 9297024
<IP of user> - - [07/Mar/2020:22:59:37 +0100] "POST /TrpServer/rest/downloadClientFileNew?isRelease=true&fileName=Transkribus-1.10.1-package.zip HTTP/1.1" 200 9264288
```
