### ISSUE TITLE
1.12.0 won't load

### ISSUE THREAD

**Issue by wujastyk** [Transkribus/TranskribusSwtGui#333]
Host: Linux Mint 20, Cinnamon.  uname -a:
```
$ uname -a
Linux Patanjali 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

I've been using 1.11 successfully.  I got the notification this week about the new version, 1.12.0.  I clicked "upgrade".  Restarted the program. Nada. 

Here is the output of trying to start from the jar.  (I normally run the Linux binary).

Is the java version critical?

```
$ java -jar Transkribus-1.12.0.jar 
11:22:35.280 INFO  [main] eu.transkribus.swt_gui.TrpGui - Working directory: /home/dom/Dropbox/bin/Transkribus-1.10.1
11:22:35.284 INFO  [main] eu.transkribus.swt_gui.TrpGui - N swtJars = 2
11:22:35.284 INFO  [main] eu.transkribus.swt_gui.TrpGui - Latest SWT version is: 4.9
11:22:35.284 INFO  [main] eu.transkribus.swt_gui.TrpGui - swt jar: swt-4.9-linux64.jar
11:22:35.284 INFO  [main] eu.transkribus.swt_gui.TrpGui - N swtJars = 2
11:22:35.284 INFO  [main] eu.transkribus.swt_gui.TrpGui - latestSwt: /home/dom/Dropbox/bin/Transkribus-1.10.1/libs/swt-4.9-linux64.jar
11:22:35.284 INFO  [main] eu.transkribus.swt_gui.TrpGui - swtLibNameFromManifest = /home/dom/Dropbox/bin/Transkribus-1.10.1/libs/swt-4.9.jar, exists: true
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/swt/widgets/Listener
	at eu.transkribus.swt_gui.TrpGui.main(TrpGui.java:176)
Caused by: java.lang.ClassNotFoundException: org.eclipse.swt.widgets.Listener
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 1 more
```

```
$ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)
```

**Comment by wujastyk** [comment]
I've answered my own question.  I see in the [wiki](https://transkribus.eu/wiki/index.php/Questions_and_Answers#How_to_download_and_install) that java 8 *is* required.  I installed openjdk jre 8 (avoiding the troublesome Oracle installation), switched to version 8:
```
sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
export PATH=$PATH:$JAVA_HOME
``` 
and then Transkribus 1.12 started just fine.
